[project]
name = "twitter-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=0.4.1",
    "requests>=2.32.3",
    "typing>=3.10.0.0",
]
